### ISSUE TITLE
cannot edit my BCO in editor

### ISSUE THREAD

**Issue by ShyanneG** [biocompute-objects/GW-SMHS-BIOC6223#198] opened 2019-10-17 13:58 UTC
Hi Janisha,
I have some trouble with using BCO Editor.
After searching by my BCO ID, I could just see two options: "read-only" and " download".
Actually, I could edit in my first edit but failed the second time I try to edit it.
Could you help me?

Best,
Yuan Gao

**Comment by jpat1546** [comment] 2019-10-17 19:40
duplicate of #216. Closing.
@ShyanneG thanks for coming to extra help- glad we were able to find a workaround.

**Closed as completed by jpat1546** 2019-10-17 19:40 UTC
Labels: BCO Editor
